<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacursos 
[ <!ELEMENT listacursos (curso+)>
<!ELEMENT curso (profesor+, alumno+, contenido)>
<!ATTLIST curso codigo CDATA #REQUIRED>
<!ELEMENT profesor (dni, nombre, ap1, ap2?)>
<!ELEMENT alumno (dni, nombre, ap1, ap2?)>
<!ELEMENT contenido (descripcion, horas, creditos?)>

<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ap1 (#PCDATA)>
<!ELEMENT ap2 (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT horas (#PCDATA)>
<!ELEMENT creditos (#PCDATA)> ]>

<listacursos>
    <curso codigo="UM">
        <profesor>
            <dni>30515455K</dni>
            <nombre>Tomas</nombre>
            <ap1>Martinez</ap1>
            <ap2>Ruiz</ap2>
        </profesor>
        <alumno>
            <dni>33354697A</dni>
            <nombre>Silvia</nombre>
            <ap1>Ruiz</ap1>
        </alumno>
        <contenido>
            <descripcion>Introduccion a los Lenguajes de Marcas</descripcion>
            <horas>200</horas>
            <creditos>4</creditos>
        </contenido>
    </curso>
</listacursos>
